// <auto-generated />
using System;
using AmazeCare.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmazeCare.Server.Migrations
{
    [DbContext(typeof(AmazeCareDBContext))]
    partial class AmazeCareDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmazeCare.Server.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Admins_UserId");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookedByUserUserId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("GeneralCheckup");

                    b.HasKey("AppointmentId");

                    b.HasIndex("BookedByUserUserId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("DoctorId", "AppointmentDate")
                        .HasDatabaseName("IX_Appointments_Doctor_Date");

                    b.HasIndex("PatientId", "AppointmentDate")
                        .HasDatabaseName("IX_Appointments_Patient_Date");

                    b.HasIndex("DoctorId", "AppointmentDate", "TimeSlot")
                        .IsUnique()
                        .HasDatabaseName("IX_Appointments_Doctor_Date_TimeSlot_Unique")
                        .HasFilter("[Status] <> 'Cancelled' AND [Status] <> 'Rejected' AND [Status] <> 'NoShow'");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Consultation", b =>
                {
                    b.Property<int>("ConsultationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultationId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConsultationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrentSymptoms")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PhysicalExamination")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TreatmentPlan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ConsultationId");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_Consultations_AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultations", (string)null);
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("AmazeCare.Server.Models.LabTest", b =>
                {
                    b.Property<int>("LabTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabTestId"));

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("TestCatalogId")
                        .HasColumnType("int");

                    b.HasKey("LabTestId");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TestCatalogId");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.LabTestCatalog", b =>
                {
                    b.Property<int>("TestCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestCatalogId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalRange")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TestCatalogId");

                    b.HasIndex("TestName")
                        .IsUnique();

                    b.ToTable("LabTestCatalogs", (string)null);

                    b.HasData(
                        new
                        {
                            TestCatalogId = 1,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "RBC: 4.5-5.5M/µL, WBC: 4000-11000/µL, Hb: 13-17 g/dL",
                            ShortName = "CBC",
                            TestName = "Complete Blood Count"
                        },
                        new
                        {
                            TestCatalogId = 2,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "ALT: 7-56 U/L, AST: 10-40 U/L, ALP: 44-147 U/L",
                            ShortName = "LFT",
                            TestName = "Liver Function Test"
                        },
                        new
                        {
                            TestCatalogId = 3,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "Creatinine: 0.6-1.2 mg/dL, Urea: 15-40 mg/dL",
                            ShortName = "KFT",
                            TestName = "Kidney Function Test"
                        },
                        new
                        {
                            TestCatalogId = 4,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "70-100 mg/dL",
                            ShortName = "FBS",
                            TestName = "Fasting Blood Sugar"
                        },
                        new
                        {
                            TestCatalogId = 5,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "< 140 mg/dL",
                            ShortName = "PPBS",
                            TestName = "Postprandial Blood Sugar"
                        },
                        new
                        {
                            TestCatalogId = 6,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "< 5.7% (Normal), 5.7-6.4% (Prediabetic)",
                            ShortName = "HbA1c",
                            TestName = "HbA1c"
                        },
                        new
                        {
                            TestCatalogId = 7,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "Total Cholesterol < 200 mg/dL, LDL < 100 mg/dL",
                            ShortName = "LP",
                            TestName = "Lipid Profile"
                        },
                        new
                        {
                            TestCatalogId = 8,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "Na: 135-145 mEq/L, K: 3.5-5.0 mEq/L",
                            ShortName = "ELEC",
                            TestName = "Serum Electrolytes"
                        },
                        new
                        {
                            TestCatalogId = 9,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "< 10 mg/L",
                            ShortName = "CRP",
                            TestName = "C-Reactive Protein"
                        },
                        new
                        {
                            TestCatalogId = 10,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "Men: < 15 mm/hr, Women: < 20 mm/hr",
                            ShortName = "ESR",
                            TestName = "Erythrocyte Sedimentation Rate"
                        },
                        new
                        {
                            TestCatalogId = 11,
                            Category = "BloodTest",
                            IsActive = true,
                            NormalRange = "INR: 0.8-1.1",
                            ShortName = "PT/INR",
                            TestName = "Prothrombin Time"
                        },
                        new
                        {
                            TestCatalogId = 12,
                            Category = "BloodTest",
                            IsActive = true,
                            ShortName = "BG",
                            TestName = "Blood Group & Rh Typing"
                        },
                        new
                        {
                            TestCatalogId = 13,
                            Category = "HormoneTest",
                            IsActive = true,
                            NormalRange = "0.4-4.0 mIU/L",
                            ShortName = "TSH",
                            TestName = "Thyroid Stimulating Hormone"
                        },
                        new
                        {
                            TestCatalogId = 14,
                            Category = "HormoneTest",
                            IsActive = true,
                            NormalRange = "2.3-4.2 pg/mL",
                            ShortName = "FT3",
                            TestName = "Free T3"
                        },
                        new
                        {
                            TestCatalogId = 15,
                            Category = "HormoneTest",
                            IsActive = true,
                            NormalRange = "0.8-1.8 ng/dL",
                            ShortName = "FT4",
                            TestName = "Free T4"
                        },
                        new
                        {
                            TestCatalogId = 16,
                            Category = "HormoneTest",
                            IsActive = true,
                            NormalRange = "TSH: 0.4-4.0 mIU/L",
                            ShortName = "TFT",
                            TestName = "Thyroid Profile (T3, T4, TSH)"
                        },
                        new
                        {
                            TestCatalogId = 17,
                            Category = "HormoneTest",
                            IsActive = true,
                            NormalRange = "Men: 270-1070 ng/dL",
                            ShortName = "TESTO",
                            TestName = "Testosterone"
                        },
                        new
                        {
                            TestCatalogId = 18,
                            Category = "HormoneTest",
                            IsActive = true,
                            NormalRange = "Men: 2-18 ng/mL, Women: 2-29 ng/mL",
                            ShortName = "PRL",
                            TestName = "Prolactin"
                        },
                        new
                        {
                            TestCatalogId = 19,
                            Category = "UrineTest",
                            IsActive = true,
                            NormalRange = "pH: 4.5-8.0, Protein: Negative, Glucose: Negative",
                            ShortName = "URE",
                            TestName = "Urine Routine Examination"
                        },
                        new
                        {
                            TestCatalogId = 20,
                            Category = "UrineTest",
                            IsActive = true,
                            NormalRange = "No growth",
                            ShortName = "UCS",
                            TestName = "Urine Culture & Sensitivity"
                        },
                        new
                        {
                            TestCatalogId = 21,
                            Category = "UrineTest",
                            IsActive = true,
                            NormalRange = "< 150 mg/day",
                            ShortName = "24UPR",
                            TestName = "24-Hour Urine Protein"
                        },
                        new
                        {
                            TestCatalogId = 22,
                            Category = "MicrobiologyTest",
                            IsActive = true,
                            NormalRange = "Negative",
                            ShortName = "NS1",
                            TestName = "Dengue NS1 Antigen"
                        },
                        new
                        {
                            TestCatalogId = 23,
                            Category = "MicrobiologyTest",
                            IsActive = true,
                            NormalRange = "Negative",
                            ShortName = "DENG-AB",
                            TestName = "Dengue IgM / IgG"
                        },
                        new
                        {
                            TestCatalogId = 24,
                            Category = "MicrobiologyTest",
                            IsActive = true,
                            NormalRange = "Negative",
                            ShortName = "MAL",
                            TestName = "Malaria Antigen Test"
                        },
                        new
                        {
                            TestCatalogId = 25,
                            Category = "MicrobiologyTest",
                            IsActive = true,
                            NormalRange = "Titer < 1:80",
                            ShortName = "WIDAL",
                            TestName = "Typhoid (Widal Test)"
                        },
                        new
                        {
                            TestCatalogId = 26,
                            Category = "MicrobiologyTest",
                            IsActive = true,
                            NormalRange = "Not Detected",
                            ShortName = "RTPCR",
                            TestName = "COVID-19 RT-PCR"
                        },
                        new
                        {
                            TestCatalogId = 27,
                            Category = "MicrobiologyTest",
                            IsActive = true,
                            NormalRange = "Negative",
                            ShortName = "RAT",
                            TestName = "COVID-19 Rapid Antigen"
                        },
                        new
                        {
                            TestCatalogId = 28,
                            Category = "MicrobiologyTest",
                            IsActive = true,
                            NormalRange = "Non-Reactive",
                            ShortName = "HIV",
                            TestName = "HIV 1 & 2 Antibody"
                        },
                        new
                        {
                            TestCatalogId = 29,
                            Category = "MicrobiologyTest",
                            IsActive = true,
                            NormalRange = "Negative",
                            ShortName = "HBsAg",
                            TestName = "Hepatitis B Surface Antigen"
                        },
                        new
                        {
                            TestCatalogId = 30,
                            Category = "MicrobiologyTest",
                            IsActive = true,
                            NormalRange = "Non-Reactive",
                            ShortName = "HCV",
                            TestName = "Hepatitis C Antibody"
                        },
                        new
                        {
                            TestCatalogId = 31,
                            Category = "CardiologyTest",
                            IsActive = true,
                            NormalRange = "Normal sinus rhythm",
                            ShortName = "ECG",
                            TestName = "Electrocardiogram"
                        },
                        new
                        {
                            TestCatalogId = 32,
                            Category = "CardiologyTest",
                            IsActive = true,
                            NormalRange = "Normal cardiac function",
                            ShortName = "ECHO",
                            TestName = "Echocardiogram"
                        },
                        new
                        {
                            TestCatalogId = 33,
                            Category = "CardiologyTest",
                            IsActive = true,
                            NormalRange = "< 0.04 ng/mL",
                            ShortName = "TROP-I",
                            TestName = "Troponin I"
                        },
                        new
                        {
                            TestCatalogId = 34,
                            Category = "Imaging",
                            IsActive = true,
                            ShortName = "CXR",
                            TestName = "Chest X-Ray"
                        },
                        new
                        {
                            TestCatalogId = 35,
                            Category = "Imaging",
                            IsActive = true,
                            ShortName = "XR",
                            TestName = "X-Ray (Other)"
                        },
                        new
                        {
                            TestCatalogId = 36,
                            Category = "Imaging",
                            IsActive = true,
                            ShortName = "USG-ABD",
                            TestName = "Ultrasound Abdomen"
                        },
                        new
                        {
                            TestCatalogId = 37,
                            Category = "Imaging",
                            IsActive = true,
                            ShortName = "USG-PEL",
                            TestName = "Ultrasound Pelvis"
                        },
                        new
                        {
                            TestCatalogId = 38,
                            Category = "Imaging",
                            IsActive = true,
                            ShortName = "CT-HEAD",
                            TestName = "CT Scan Head"
                        },
                        new
                        {
                            TestCatalogId = 39,
                            Category = "Imaging",
                            IsActive = true,
                            ShortName = "CT-ABD",
                            TestName = "CT Scan Abdomen"
                        },
                        new
                        {
                            TestCatalogId = 40,
                            Category = "Imaging",
                            IsActive = true,
                            ShortName = "MRI-B",
                            TestName = "MRI Brain"
                        },
                        new
                        {
                            TestCatalogId = 41,
                            Category = "Imaging",
                            IsActive = true,
                            ShortName = "MRI-SP",
                            TestName = "MRI Spine"
                        },
                        new
                        {
                            TestCatalogId = 42,
                            Category = "Biopsy",
                            IsActive = true,
                            ShortName = "FNAC",
                            TestName = "Fine Needle Aspiration Cytology"
                        },
                        new
                        {
                            TestCatalogId = 43,
                            Category = "Biopsy",
                            IsActive = true,
                            ShortName = "HPE",
                            TestName = "Histopathology"
                        });
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultDosage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MedicineId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Medicines", (string)null);

                    b.HasData(
                        new
                        {
                            MedicineId = 1,
                            Category = "Antipyretic",
                            DefaultDosage = "500mg",
                            GenericName = "Acetaminophen",
                            IsActive = true,
                            Name = "Paracetamol 500mg"
                        },
                        new
                        {
                            MedicineId = 2,
                            Category = "Antipyretic",
                            DefaultDosage = "650mg",
                            GenericName = "Acetaminophen",
                            IsActive = true,
                            Name = "Paracetamol 650mg"
                        },
                        new
                        {
                            MedicineId = 3,
                            Category = "Analgesic",
                            DefaultDosage = "400mg",
                            GenericName = "Ibuprofen",
                            IsActive = true,
                            Name = "Ibuprofen 400mg"
                        },
                        new
                        {
                            MedicineId = 4,
                            Category = "Analgesic",
                            DefaultDosage = "50mg",
                            GenericName = "Diclofenac Sodium",
                            IsActive = true,
                            Name = "Diclofenac 50mg"
                        },
                        new
                        {
                            MedicineId = 5,
                            Category = "Antibiotic",
                            DefaultDosage = "250mg",
                            GenericName = "Amoxicillin",
                            IsActive = true,
                            Name = "Amoxicillin 250mg"
                        },
                        new
                        {
                            MedicineId = 6,
                            Category = "Antibiotic",
                            DefaultDosage = "500mg",
                            GenericName = "Amoxicillin",
                            IsActive = true,
                            Name = "Amoxicillin 500mg"
                        },
                        new
                        {
                            MedicineId = 7,
                            Category = "Antibiotic",
                            DefaultDosage = "250mg",
                            GenericName = "Azithromycin",
                            IsActive = true,
                            Name = "Azithromycin 250mg"
                        },
                        new
                        {
                            MedicineId = 8,
                            Category = "Antibiotic",
                            DefaultDosage = "500mg",
                            GenericName = "Azithromycin",
                            IsActive = true,
                            Name = "Azithromycin 500mg"
                        },
                        new
                        {
                            MedicineId = 9,
                            Category = "Antibiotic",
                            DefaultDosage = "500mg",
                            GenericName = "Ciprofloxacin",
                            IsActive = true,
                            Name = "Ciprofloxacin 500mg"
                        },
                        new
                        {
                            MedicineId = 10,
                            Category = "Antibiotic",
                            DefaultDosage = "100mg",
                            GenericName = "Doxycycline",
                            IsActive = true,
                            Name = "Doxycycline 100mg"
                        },
                        new
                        {
                            MedicineId = 11,
                            Category = "Antacid",
                            DefaultDosage = "20mg",
                            GenericName = "Omeprazole",
                            IsActive = true,
                            Name = "Omeprazole 20mg"
                        },
                        new
                        {
                            MedicineId = 12,
                            Category = "Antacid",
                            DefaultDosage = "40mg",
                            GenericName = "Pantoprazole",
                            IsActive = true,
                            Name = "Pantoprazole 40mg"
                        },
                        new
                        {
                            MedicineId = 13,
                            Category = "Antacid",
                            DefaultDosage = "150mg",
                            GenericName = "Ranitidine",
                            IsActive = true,
                            Name = "Ranitidine 150mg"
                        },
                        new
                        {
                            MedicineId = 14,
                            Category = "Antacid",
                            DefaultDosage = "10mg",
                            GenericName = "Domperidone",
                            IsActive = true,
                            Name = "Domperidone 10mg"
                        },
                        new
                        {
                            MedicineId = 15,
                            Category = "Antihistamine",
                            DefaultDosage = "10mg",
                            GenericName = "Cetirizine",
                            IsActive = true,
                            Name = "Cetirizine 10mg"
                        },
                        new
                        {
                            MedicineId = 16,
                            Category = "Antihistamine",
                            DefaultDosage = "10mg",
                            GenericName = "Loratadine",
                            IsActive = true,
                            Name = "Loratadine 10mg"
                        },
                        new
                        {
                            MedicineId = 17,
                            Category = "Antihistamine",
                            DefaultDosage = "4mg",
                            GenericName = "Chlorpheniramine",
                            IsActive = true,
                            Name = "Chlorpheniramine 4mg"
                        },
                        new
                        {
                            MedicineId = 18,
                            Category = "Antidiabetic",
                            DefaultDosage = "500mg",
                            GenericName = "Metformin",
                            IsActive = true,
                            Name = "Metformin 500mg"
                        },
                        new
                        {
                            MedicineId = 19,
                            Category = "Antidiabetic",
                            DefaultDosage = "1000mg",
                            GenericName = "Metformin",
                            IsActive = true,
                            Name = "Metformin 1000mg"
                        },
                        new
                        {
                            MedicineId = 20,
                            Category = "Antidiabetic",
                            DefaultDosage = "5mg",
                            GenericName = "Glibenclamide",
                            IsActive = true,
                            Name = "Glibenclamide 5mg"
                        },
                        new
                        {
                            MedicineId = 21,
                            Category = "Antidiabetic",
                            DefaultDosage = "2mg",
                            GenericName = "Glimepiride",
                            IsActive = true,
                            Name = "Glimepiride 2mg"
                        },
                        new
                        {
                            MedicineId = 22,
                            Category = "Antihypertensive",
                            DefaultDosage = "5mg",
                            GenericName = "Amlodipine",
                            IsActive = true,
                            Name = "Amlodipine 5mg"
                        },
                        new
                        {
                            MedicineId = 23,
                            Category = "Antihypertensive",
                            DefaultDosage = "10mg",
                            GenericName = "Amlodipine",
                            IsActive = true,
                            Name = "Amlodipine 10mg"
                        },
                        new
                        {
                            MedicineId = 24,
                            Category = "Antihypertensive",
                            DefaultDosage = "50mg",
                            GenericName = "Losartan",
                            IsActive = true,
                            Name = "Losartan 50mg"
                        },
                        new
                        {
                            MedicineId = 25,
                            Category = "Antihypertensive",
                            DefaultDosage = "50mg",
                            GenericName = "Atenolol",
                            IsActive = true,
                            Name = "Atenolol 50mg"
                        },
                        new
                        {
                            MedicineId = 26,
                            Category = "Vitamin",
                            DefaultDosage = "500mg",
                            GenericName = "Ascorbic Acid",
                            IsActive = true,
                            Name = "Vitamin C 500mg"
                        },
                        new
                        {
                            MedicineId = 27,
                            Category = "Vitamin",
                            DefaultDosage = "60000IU",
                            GenericName = "Cholecalciferol",
                            IsActive = true,
                            Name = "Vitamin D3 60000 IU"
                        },
                        new
                        {
                            MedicineId = 28,
                            Category = "Vitamin",
                            DefaultDosage = "500mcg",
                            GenericName = "Cyanocobalamin",
                            IsActive = true,
                            Name = "Vitamin B12 500mcg"
                        },
                        new
                        {
                            MedicineId = 29,
                            Category = "Supplement",
                            DefaultDosage = "500mg",
                            GenericName = "Calcium Carbonate",
                            IsActive = true,
                            Name = "Calcium + Vitamin D3"
                        },
                        new
                        {
                            MedicineId = 30,
                            Category = "Supplement",
                            DefaultDosage = "150mg",
                            GenericName = "Ferrous Sulfate",
                            IsActive = true,
                            Name = "Iron + Folic Acid"
                        },
                        new
                        {
                            MedicineId = 31,
                            Category = "Antifungal",
                            DefaultDosage = "150mg",
                            GenericName = "Fluconazole",
                            IsActive = true,
                            Name = "Fluconazole 150mg"
                        },
                        new
                        {
                            MedicineId = 32,
                            Category = "Antifungal",
                            DefaultDosage = "1%",
                            GenericName = "Clotrimazole",
                            IsActive = true,
                            Name = "Clotrimazole 1% Cream"
                        },
                        new
                        {
                            MedicineId = 33,
                            Category = "Antiviral",
                            DefaultDosage = "400mg",
                            GenericName = "Acyclovir",
                            IsActive = true,
                            Name = "Acyclovir 400mg"
                        },
                        new
                        {
                            MedicineId = 34,
                            Category = "Antiviral",
                            DefaultDosage = "75mg",
                            GenericName = "Oseltamivir",
                            IsActive = true,
                            Name = "Oseltamivir 75mg"
                        },
                        new
                        {
                            MedicineId = 35,
                            Category = "Steroid",
                            DefaultDosage = "5mg",
                            GenericName = "Prednisolone",
                            IsActive = true,
                            Name = "Prednisolone 5mg"
                        },
                        new
                        {
                            MedicineId = 36,
                            Category = "Steroid",
                            DefaultDosage = "0.5mg",
                            GenericName = "Dexamethasone",
                            IsActive = true,
                            Name = "Dexamethasone 0.5mg"
                        },
                        new
                        {
                            MedicineId = 37,
                            Category = "Bronchodilator",
                            DefaultDosage = "2mg",
                            GenericName = "Salbutamol",
                            IsActive = true,
                            Name = "Salbutamol 2mg"
                        },
                        new
                        {
                            MedicineId = 38,
                            Category = "Bronchodilator",
                            DefaultDosage = "10mg",
                            GenericName = "Montelukast",
                            IsActive = true,
                            Name = "Montelukast 10mg"
                        },
                        new
                        {
                            MedicineId = 39,
                            Category = "Diuretic",
                            DefaultDosage = "40mg",
                            GenericName = "Furosemide",
                            IsActive = true,
                            Name = "Furosemide 40mg"
                        },
                        new
                        {
                            MedicineId = 40,
                            Category = "Diuretic",
                            DefaultDosage = "25mg",
                            GenericName = "Spironolactone",
                            IsActive = true,
                            Name = "Spironolactone 25mg"
                        });
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrescribedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("ConsultationId")
                        .IsUnique()
                        .HasDatabaseName("IX_Prescriptions_ConsultationId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("AmazeCare.Server.Models.PrescriptionItem", b =>
                {
                    b.Property<int>("PrescriptionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionItemId"));

                    b.Property<bool>("Afternoon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Dosage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("Evening")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("FoodInstruction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("AfterFood");

                    b.Property<string>("Instructions")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<bool>("Morning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Night")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionItemId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems", (string)null);
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecializationId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Specializations_Name");

                    b.ToTable("Specializations", (string)null);

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            IsActive = true,
                            Name = "General Medicine"
                        },
                        new
                        {
                            SpecializationId = 2,
                            IsActive = true,
                            Name = "Obstetrics and Gynecology"
                        },
                        new
                        {
                            SpecializationId = 3,
                            IsActive = true,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            SpecializationId = 4,
                            IsActive = true,
                            Name = "Cardiology"
                        },
                        new
                        {
                            SpecializationId = 5,
                            IsActive = true,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            SpecializationId = 6,
                            IsActive = true,
                            Name = "Dermatology"
                        },
                        new
                        {
                            SpecializationId = 7,
                            IsActive = true,
                            Name = "Neurology"
                        },
                        new
                        {
                            SpecializationId = 8,
                            IsActive = true,
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            SpecializationId = 9,
                            IsActive = true,
                            Name = "ENT"
                        },
                        new
                        {
                            SpecializationId = 10,
                            IsActive = true,
                            Name = "Psychiatry"
                        },
                        new
                        {
                            SpecializationId = 11,
                            IsActive = true,
                            Name = "Urology"
                        },
                        new
                        {
                            SpecializationId = 12,
                            IsActive = true,
                            Name = "Gastroenterology"
                        },
                        new
                        {
                            SpecializationId = 13,
                            IsActive = true,
                            Name = "Pulmonology"
                        },
                        new
                        {
                            SpecializationId = 14,
                            IsActive = true,
                            Name = "Endocrinology"
                        },
                        new
                        {
                            SpecializationId = 15,
                            IsActive = true,
                            Name = "Oncology"
                        },
                        new
                        {
                            SpecializationId = 16,
                            IsActive = true,
                            Name = "Nephrology"
                        },
                        new
                        {
                            SpecializationId = 17,
                            IsActive = true,
                            Name = "Rheumatology"
                        },
                        new
                        {
                            SpecializationId = 18,
                            IsActive = true,
                            Name = "Emergency Medicine"
                        });
                });

            modelBuilder.Entity("AmazeCare.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_PhoneNumber");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Admin", b =>
                {
                    b.HasOne("AmazeCare.Server.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("AmazeCare.Server.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Appointment", b =>
                {
                    b.HasOne("AmazeCare.Server.Models.User", "BookedByUser")
                        .WithMany()
                        .HasForeignKey("BookedByUserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId");

                    b.Navigation("BookedByUser");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Consultation", b =>
                {
                    b.HasOne("AmazeCare.Server.Models.Appointment", "Appointment")
                        .WithOne("Consultation")
                        .HasForeignKey("AmazeCare.Server.Models.Consultation", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Doctor", "Doctor")
                        .WithMany("Consultations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Doctor", b =>
                {
                    b.HasOne("AmazeCare.Server.Models.Specialization", "Specialization")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("AmazeCare.Server.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.LabTest", b =>
                {
                    b.HasOne("AmazeCare.Server.Models.Consultation", "Consultation")
                        .WithMany("LabTests")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Patient", "Patient")
                        .WithMany("LabTests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.LabTestCatalog", "TestCatalog")
                        .WithMany("LabTests")
                        .HasForeignKey("TestCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("TestCatalog");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Patient", b =>
                {
                    b.HasOne("AmazeCare.Server.Models.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Prescription", b =>
                {
                    b.HasOne("AmazeCare.Server.Models.Consultation", "Consultation")
                        .WithOne("Prescription")
                        .HasForeignKey("AmazeCare.Server.Models.Prescription", "ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.PrescriptionItem", b =>
                {
                    b.HasOne("AmazeCare.Server.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmazeCare.Server.Models.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Appointment", b =>
                {
                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Consultation", b =>
                {
                    b.Navigation("LabTests");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.LabTestCatalog", b =>
                {
                    b.Navigation("LabTests");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Medicine", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Consultations");

                    b.Navigation("LabTests");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.Specialization", b =>
                {
                    b.Navigation("DoctorSpecializations");
                });

            modelBuilder.Entity("AmazeCare.Server.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Doctor");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
